#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# disable laptop touch screen
#xinput disable 'ELAN Touchscreen'

# keyboard delay and repeat rate
#xset r rate 130 50

# enable key bindings set in ~/.xbindkeysrc
xbindkeys --poll-rc

# notification daemon
#lxqt-notificationd &!

xsetroot -cursor_name left_ptr

export _JAVA_AWT_WM_NONREPARENTING=1

xmonad
