#!/bin/sh
# This script creates symlinks from the files within this repo to the actual system files

# Absolute path to this script
SCRIPT_PATH=`readlink -f $0`

# Absolute path this script is in
SCRIPT_DIR=`dirname $SCRIPT_PATH`
BASE_DIR=`dirname $SCRIPT_DIR`

echo "Linking config files from $BASE_DIR..."

link() {
    FROM="$BASE_DIR/$1"
    TO=$2
    printf "ln -s %s %s\n" $FROM $TO
    rm $TO
    ln -s $FROM $TO
}

mkdir -p ~/.config

# Installs oh-my-zsh
if [ ! -d "/home/gustavo/.oh-my-zsh/" ]; then
    echo "Installing oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
link oh-my-zsh/themes ~/.oh-my-zsh/custom/themes

link zshrc ~/.zshrc
link scripts ~/.scripts
link scripts/updates ~/.local/bin/updates
link gitconfig ~/.gitconfig
link Xresources ~/.Xresources
link xsessionrc ~/.xsessionrc

link vim ~/.vim
# Installs vim-plug
if [ ! -f "/home/gustavo/.vim/autoload/plug.vim" ]; then
    echo "Installing vim-plug..."
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

mkdir -p ~/.xmonad
link xmonad/xmonad.hs ~/.xmonad/xmonad.hs

mkdir -p ~/.config/xmobar
link xmobar/xmobarrc ~/.config/xmobar/xmobarrc
link xmobar/xmobarrc-laptop ~/.config/xmobar/xmobarrc-laptop

mkdir -p ~/.config/redshift
link redshift/redshift.conf ~/.config/redshift/redshift.conf

mkdir -p ~/.bloop
link bloop.json ~/.bloop/bloop.json

mkdir -p ~/.config/systemd/user
for filepath in $BASE_DIR/systemd/*.service; do
    filename=$(basename $filepath)
    link systemd/$filename ~/.config/systemd/user/$filename
done

systemctl --user daemon-reload
