[general]
import = ["theme.toml"]

[font]
size = 8.5

[font.normal]
family = "SFMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SFMono Nerd Font Mono"
style = "Italic"
